### ISSUE TITLE
Accented characters not displaying correctly

### ISSUE THREAD

**Issue by lebdev** [gitrows/gitrows#33] opened 2021-12-16 05:49 UTC
**Describe the bug**
I have in my .json file some accented characters.
When I fetch the data, all accented characters are not displayed correctly.
For example :
**é** is displayed as **Ã©** and so on...

**Expected behavior**
Should display accented characters correctly.

**Additional context**
My file is in a private repository.

Thanks a lot for your time and efforts

**Comment by lebdev** [comment] 2021-12-16 21:16
Hello,
Just so you can see what I'm talking about, I've create 2 repositories, one private and one public, with the same object in a json file.
Then, I've used gitrows to get the content in the console, side by side.
As you can see, the private repository does not return accented characters correctly
![privateVSpublic](https://user-images.githubusercontent.com/63741630/146450042-99cff2a1-d76a-45c4-80f7-44ddde388375.png)
.

**Comment by LebCit** [comment] 2021-12-20 15:50
Hello,

After searching a little bit, I've found [this solution](https://stackoverflow.com/a/30106551) to decode base64 to UTF8
Then, after unminifying gitrows.min.js, on line 5340, I've replaced :
```js
atob: (e) => ("undefined" == typeof window ? t.from(e, "base64").toString("utf-8") : window.atob(e))
```
with :
```js
atob: (e) => ("undefined" == typeof window ? t.from(e, "base64").toString("utf-8") : decodeURIComponent(window.atob(e).split('').map(function (c) {
    return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
}).join('')))
```
Tested get, put, update and delete, everything works well.

Hope this helps.

Have a nice coding day/night !

SYA

**Comment by nicolaszimmer** [comment] 2022-03-07 15:40
Sorry for the late reply. The different handling of private and public repos contents is due to the way the data is fetched from GitHub. Private repos are always retrieved via API and thus base64 encoded. So this explains your observation. 

However I was unable to reproduce the behavior, probably because the atob bug was fixed in the meantime. What node version have you been running into this problem?

And thanks a lot for the proposed fix!

**Closed as completed** 2022-05-02 13:40 UTC
